dist: bionic

cache: packages

jobs:
  include:

    # - name: venv_py3
    #   addons:
    #     apt:
    #       sources:
    #       - ubuntu-toolchain-r-test
    #       packages:
    #       - g++-7
    #   before_install: 
    #   - sudo apt-get update
    #   - sudo apt-get -y install build-essential mpich libmpich-dev
    #   script:
    #   - virtualenv -p python3 .venv
    #   - source .venv/bin/activate
    #   - pip install -U numpy pandas pybind11
    #   - make && make test
    #   - make -f MPI.mk && make -f MPI.mk test

    - name: conda_py3
      before_install: 
      - | 
        wget -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash miniconda.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        conda config --set always_yes yes --set changeps1 no
        conda config --add channels conda-forge
        conda update -q conda
        conda install -q conda-build
        conda create -q -n test-environment python=3.8
        source activate test-environment      
      install:
        - conda install gxx_linux-64 openssl mpich numpy pandas pybind11 pytest
      script:
      - |
        python setup.py install
        pytest
        mpiexec -n 2 pytest
        make && make test
        make -f MPI.mk && make -f MPI.mk test

    - language: python
      python: 3.6
      before_install:
      - sudo apt-get update
      - sudo apt-get -y install build-essential mpich libmpich-dev
      install: 
      - pip install pybind11 numpy pandas mpi4py
      script:
      - python setup.py install
      - python setup.py test
      - mpiexec -n 2 pytest
      - make PY_CFG=python-config PY_CFG_LINK_ARG="" && make test
      - make PY_CFG=python-config PY_CFG_LINK_ARG="" -f MPI.mk && make -f MPI.mk test

    - language: python
      python: 3.7
      before_install: 
      - sudo apt-get update
      - sudo apt-get -y install build-essential mpich libmpich-dev python3.7-dev 
      install: 
      - pip install pybind11 numpy pandas mpi4py
      script:
      - python setup.py install
      - python setup.py test
      - mpiexec -n 2 pytest
      - make PY_CFG=python-config PY_CFG_LINK_ARG="" && make test
      - make PY_CFG=python-config PY_CFG_LINK_ARG="" -f MPI.mk && make -f MPI.mk test

    - language: python
      python: 3.8
      before_install:
      - sudo apt-get update
      - sudo apt-get -y install build-essential mpich libmpich-dev python3.8-dev 
      install: 
      - pip install pybind11 numpy pandas mpi4py
      script:
      - python setup.py install
      - python setup.py test
      - mpiexec -n 2 pytest
      - make PY_CFG=python-config PY_CFG_LINK_ARG="" && make test
      - make PY_CFG=python-config PY_CFG_LINK_ARG="" -f MPI.mk && make -f MPI.mk test

    - os: osx
      osx_image: xcode11.2
      language: shell
      #before_install:
      # - brew update
      # - brew unlink python@2
      # - brew upgrade python
      #- brew install python3
      #  - python3 -m pip install numpy distutils pytest
      install: pip3 install --upgrade pip
      script:
        - python3 setup.py install
        - python3 setup.py test
        #- mpiexec -n 2 pytest

  allow_failures:
    - os: osx
    # - name: conda_py3
    # - python: 3.8

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change
  slack: mopdgroup:2uLyKWgYi8WCtv6WuTA4s0wD
