# Build environments

image:
  - Visual Studio 2019

environment:
  matrix:
   - PYTHON: "C:\\Python36-x64"
     PYTHON_ARCH: 64
     MSVC_VERSION: "Visual Studio 19 Win64"

   - PYTHON: "C:\\Python37-x64"
     PYTHON_ARCH: 64
     MSVC_VERSION: "Visual Studio 19 Win64"

   - PYTHON: "C:\\Python38-x64"
     PYTHON_ARCH: 64
     MSVC_VERSION: "Visual Studio 19 Win64"

# fail fast
matrix:
  fast_finish: true

init:
  - ps: |
      Write-Host "$env:PYTHON $env:PYTHON_ARCH $env:MSVC_VERSION"
      $python = $env:PYTHON + "\python.exe"
      & $python --version

install:
  - ps: |
      $python = $env:PYTHON + "\python.exe"
      & $python -m pip install --upgrade pip wheel setuptools --no-warn-script-location
      & $python -m pip install numpy pandas mpi4py --no-warn-script-location


build_script:
  - cmd: ("%PYTHON%\python.exe" setup.py install)

# TODO run in MPI mode also 
test_script:
  - cmd: ("%PYTHON%\\python.exe" setup.py test)


notifications:
  - provider: Email
    to:
    - '{{commitAuthorEmail}}'
    on_build_failure: true
  - provider: Slack
    incoming_webhook:
      secure: TgkWvYaiFVyz5lbNkDXlHJmYThnK+VJ3C07q7N5BE9pxgpMkDKDSY+7Mc9NLxZngJ18ErQll/v9GxuDqG/9qHIFs3EuJ9Sh3XVaEkKyJBsZOWFfP/mWY+pQljqjNxsWm
