# Build environments

environment:
  matrix:

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python37-x64"
      PYTHON_ARCH: 64
      MSVC_VERSION: "Visual Studio 19 Win64"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python38-x64"
      PYTHON_ARCH: 64
      MSVC_VERSION: "Visual Studio 19 Win64"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python39-x64"
      PYTHON_ARCH: 64
      MSVC_VERSION: "Visual Studio 19 Win64"

    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    #   MINICONDA: "C:\\Miniconda38-x64"

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.7"
      APPVEYOR_YML_DISABLE_PS_LINUX: true

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      PYTHON: "3.8"
      APPVEYOR_YML_DISABLE_PS_LINUX: true

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      PYTHON: "3.9"
      APPVEYOR_YML_DISABLE_PS_LINUX: true

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      MINICONDA: true
      PYTHON: "3.8"
      APPVEYOR_YML_DISABLE_PS_LINUX: true

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      CODECOV_BUILD: true
      PYTHON: "3.8"
      APPVEYOR_YML_DISABLE_PS_LINUX: true

    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
      PYTHON: "3.7"
      APPVEYOR_YML_DISABLE_PS_LINUX: true

    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
      PYTHON: "3.8"
      APPVEYOR_YML_DISABLE_PS_LINUX: true

    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
      PYTHON: "3.9"
      APPVEYOR_YML_DISABLE_PS_LINUX: true

stack: python %PYTHON%

# matrix:
#   allow_failures:
#     - PYTHON: "C:\\Python36-x64"
#   # fail fast
#   #fast_finish: true

install:
  # - cmd: |
  #     curl -fSs -o c:\msmpisetup.exe https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisetup.exe
  #     rem c:\msmpisetup.exe -unattend The system cannot execute the specified program.
  #     %PYTHON%\python.exe -m pip install --upgrade pip wheel setuptools --no-warn-script-location
  - ps: |
      Start-FileDownload 'https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisetup.exe'
      .\msmpisetup.exe -unattend # TODO this doesnt seem to do anything
      $python = $env:PYTHON + "\python.exe"
      & $python -m pip install --upgrade pip wheel setuptools mpi4py pytest --no-warn-script-location
  - sh: |
      if [ "$APPVEYOR_BUILD_WORKER_IMAGE" == "macOS" ]; then
      brew update && brew install open-mpi
      else
      if [ "$MINICONDA" == "true" ]; then
      scripts/create-conda-env.sh
      else
      sudo apt update && sudo apt install -y mpich libmpich-dev
      fi
      fi
      python -m pip install pytest

build_script:
  - cmd: '%PYTHON%\python.exe -m pip install .'
  - sh: |
      if [ "$CODECOV_BUILD" == "true" ]; then
      export CFLAGS=--coverage
      gcc --version # things go badly wrong is gcc and gcov versions arent in sync
      gcov --version
      elif [ "$MINICONDA" == "true" ]; then
      source "${HOME}/.miniconda/etc/profile.d/conda.sh"
      conda activate conda-env
      fi
      python -m pip install -e .

test_script:
  - cmd: '%PYTHON%\python.exe -m pytest'
  - sh: |
      if [ "$MINICONDA" == "true" ]; then
      source "${HOME}/.miniconda/etc/profile.d/conda.sh"
      conda activate conda-env
      fi
      python -m pytest && mpiexec -n 2 python -m pytest
      if [ "$CODECOV_BUILD" == "true" ]; then
      env
      bash <(curl -s https://codecov.io/bash) -Z
      fi

notifications:
  - provider: Email
    to:
    - '{{commitAuthorEmail}}'
    on_build_success: false
  - provider: Slack
    incoming_webhook:
      secure: TgkWvYaiFVyz5lbNkDXlHJmYThnK+VJ3C07q7N5BE9pxgpMkDKDSY+7Mc9NLxZngJ18ErQll/v9GxuDqG/9qHIFs3EuJ9Sh3XVaEkKyJBsZOWFfP/mWY+pQljqjNxsWm
