# Build environments

# TODO this script needs tidying

image:
  - Visual Studio 2019

environment:
  matrix:
   - TEST_LANGUAGE: "Python"
     PYTHON: "C:\\Python36-x64"
     PYTHON_ARCH: 64
     MSVC_VERSION: "Visual Studio 19 Win64"

   - TEST_LANGUAGE: "Python"
     PYTHON: "C:\\Python37-x64"
     PYTHON_ARCH: 64
     MSVC_VERSION: "Visual Studio 19 Win64"

   - TEST_LANGUAGE: "Python"
     PYTHON: "C:\\Python38-x64"
     PYTHON_ARCH: 64
     MSVC_VERSION: "Visual Studio 19 Win64"

# fail fast
matrix:
  fast_finish: true

init:
  - ps: |
      if ($env:TEST_LANGUAGE -eq "Python") {
        Write-Host "$env:PYTHON $env:PYTHON_ARCH $env:MSVC_VERSION"
        $python = $env:PYTHON + "\python.exe"
        & $python --version
      }

install:
  - ps: |
      if ($env:TEST_LANGUAGE -eq "Python") {
        $python = $env:PYTHON + "\python.exe"
        & $python -m pip install --upgrade pip wheel setuptools --no-warn-script-location
        & $python -m pip install numpy pandas mpi4py --no-warn-script-location
      }

cache:
  - C:\RLibrary

build_script:
  # install deps
  - ps: if ($env:TEST_LANGUAGE -eq "R") { TravisTool install_deps }

test_script:
  - ps: if ($env:TEST_LANGUAGE -eq "R") { TravisTool run_tests }
  - cmd: if "%TEST_LANGUAGE%" == "Python" ( "%PYTHON%\python.exe" setup.py test ) else ( echo %TEST_LANGUAGE% )

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: dist\*
    name: Dist

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
