site_name: neworder
site_url: https://neworder.readthedocs.io
site_author: Andrew P Smith
site_description: Documentation for the neworder microsimulation framework
repo_url: https://github.com/virgesmith/neworder
repo_name: GitHub
copyright: >
  Copyright &copy; 2017-2023 Andrew P Smith –
  <a href="#__consent">Change cookie settings</a>

theme:
  name: material
  palette:
    scheme: default
    primary: light blue
    accent: red
  features:
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - toc:
      permalink: "¶"
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - attr_list
  - md_in_html

extra_javascript:
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - macros:
      module_name: docs/macros
      # include_dir: examples
  - mkdocs-video

extra:
  consent:
    title: Cookie consent
    description: >-
      This site uses cookies with your permission.
    actions:
      - accept
      - manage
      - reject

nav:
  - Home: index.md
  - Overview: overview.md
  - Examples:
    - Hello World: examples/hello-world.md
    - Parallel: examples/parallel.md
    - Markov Chain: examples/markov-chain.md
    - Chapter 1: examples/chapter1.md
    - Mortality: examples/mortality.md
    - Competing: examples/competing.md
    - RiskPaths: examples/riskpaths.md
    - People: ./examples/people.md
    - Option: examples/option.md
    - Conway: examples/conway.md
    - Schelling: examples/schelling.md
    - Wolf-Sheep: examples/wolf-sheep.md
    - Boids: examples/boids.md
    - Infection: examples/infection.md
  - API:
    - Tips and Tricks: tips.md
    - API Reference: api.md
  - References: references.md
  - About:
    - Citing: citing.md
    - Contributing: contributing.md
    - Developer: developer.md
    - Support: support.md
    - Licence: licence.md

