site_name: neworder
site_url: https://neworder.readthedocs.io
site_author: Andrew P Smith
site_description: Documentation for the neworder microsimulation framework
repo_url: https://github.com/virgesmith/neworder
repo_name: GitHub
copyright: "&copy 2020 Andrew P Smith"
#google_analytics

theme:
  name: material
  palette:
    scheme: default
    primary: blue grey
    accent: red

markdown_extensions:
  - toc:
      permalink: "¶"  
  - admonition      
  - codehilite
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
      
plugins:
  - search
  - macros:
      module_name: docs.macros
      # include_dir: examples
#  - mkpdfs
#  - mkdocstrings

nav:
  - Home: index.md
  - Description: description.md
  - Examples:
    - Hello World: examples/hello_world.md
    - Parallel: examples/parallel.md
    - Markov Chain: examples/markov_chain.md
    - Chapter 1: examples/chapter1.md
    - Mortality: examples/mortality.md
    - Competing: examples/competing.md
    - RiskPaths: examples/riskpaths.md
    #- Disease: examples/disease.md
    - People: ./examples/people.md
    - Option: examples/option.md
    #- People (parallel): ./examples/people_multi.md
    - Schelling: examples/schelling.md
  - API:
    - API Reference: api.md
    - Tips and Tricks: tips.md
  - References: references.md
  - About: 
    - Citing: citing.md
    - Contributing: developer.md
    - Support: support.md
    - Licence: licence.md
#  - 'test.md'

