site_name: neworder
site_url: https://neworder.readthedocs.io
site_author: Andrew P Smith
site_description: Documentation for the neworder microsimulation framework
#extra_javascript:
#extra_css:
repo_url: https://github.com/virgesmith/neworder
repo_name: GitHub
copyright: &copy 2020 Andrew P Smith
#google_analytics

theme:
  name: material
  # highlightjs: true
  # hljs_languages:
  #     - yaml
  #     - rust

markdown_extensions:
  - toc:
      permalink: "¶"  
  - admonition      


# plugins:
#   - search
#   - mkdocstrings
  
  # extra:
  #   include_toc: yes      
  #   extra_nav_links:
  #     Fork me on GitHub: https://github.com/iamale/rock-cli

nav:
  - Description: description.md
  - Examples:
    - Hello World: examples/hello_world.md
    - Parallel: examples/parallel.md
    - Markov Chain: examples/markov_chain.md
    - Chapter1: examples/chapter1.md
    - Mortality: examples/mortality.md
    - Option: examples/option.md
    - Competing: examples/competing.md
    - Disease: examples/disease.md
    - People: ./examples/people.md
    - People (parallel): ./examples/people_multi.md
    - RiskPaths: examples/riskpaths.md
    - Schelling: examples/schelling.md
  - API:
    - API Reference: api_auto.md
    - Tips and Tricks: tips.md
  - References: references.md
  - About: 
    - Citing: citing.md
    - Contributing: developer.md
    - Support: support.md
    - Licence: licence.md
#  - 'test.md'

