# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' TODO documentation
#'
#' @return a List .
#' @examples
#' #TODO
#' @export
urand01_vector <- function(length) {
    .Call(`_neworder_urand01_vector`, length)
}

#' TODO documentation
#'
#' @return a List .
#' @examples
#' #TODO
#' @export
select_at_random <- function(input, drivingColumn, probs) {
    .Call(`_neworder_select_at_random`, input, drivingColumn, probs)
}

#' TODO documentation
#'
#' @return a List .
#' @examples
#' #TODO
#' @export
age_column <- function(input, colName) {
    .Call(`_neworder_age_column`, input, colName)
}

