
name: Python coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8 ]
    steps:
    - uses: actions/checkout@v2
    - name: "pip: Python ${{ matrix.python-version }} coverage"
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pybind11 pytest
    - name: Build
      run: |
        CFLAGS=-coverage python -m pip install .
    - name: Test
      run: |
        python -m pytest
    - name: Upload
      run: |
        bash <(curl -s https://codecov.io/bash) -Z
