
name: Code coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12" ]
    steps:
    - uses: actions/checkout@v4
    - name: "pip: Python ${{ matrix.python-version }} coverage"
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pybind11 pytest
    - name: Build
      run: |
        CXXFLAGS=-coverage python -m pip install .
    - name: Test
      run: |
        python -m pytest
    - name: Upload
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        bash <(curl -s https://codecov.io/bash) -Z
